---
- name: Set-SSH-key-manual
  hosts: all
  gather_facts: yes
  vars:
    sshpubkey: pubkey

  tasks:    
  - name: Set authorized keys taken from url\inserted
    authorized_key:
     user: ubuntu
     state: present
     key: "{{sshpubkey}}"

  - name: Reload service sshd
    service:
      name: sshd
      state: reloaded