---
- name: Set only management keys and remove others
  hosts: "{{selhosts}}"
  gather_facts: yes
  become: yes
  vars:
    selhosts:
      - all
      - monitoring
      - prodservers
      - testservers
      - webservers
      - agilelocalinfra
      - jenkinsservers

  tasks:
  - name: Connection Check
    ping:

  - name: Checking for management keys and sync root
    authorized_key:
      user: root
      state: present
      exclusive: yes
      key: "{{ lookup('file', '/root/keyslist/management.keys') }}"

  - name: Checking for management keys and sync ubuntu
    authorized_key:
      user: ubuntu
      state: present
      key: "{{ lookup('file', '/root/keyslist/management.keys') }}"
  
  - name: Reload service sshd
    service:
      name: sshd
      state: reloaded